rename autogen to AG2 in website
ag2ai/ag2 pull request #24
Opened 2024-11-16 21:01 UTC by skzhang1

## Why are these changes needed?
rename autogen to AG2 in website

## Related issue number

## Checks

- [x] I've included any doc changes needed for https://ag2ai.github.io/autogen/. See https://ag2ai.github.io/ag2/docs/Contribute#documentation to build and test documentation locally.
- [x] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [x] I've made sure all auto checks have passed.

2024-11-16 23:24 UTC, sonichi requested changes

2024-11-16 23:24 UTC, sonichi commented on NOTICE.md
> +This project is a fork of https://github.com/ag2ai/ag2.
Remove this change

2024-11-16 23:24 UTC, sonichi commented on NOTICE.md
> +The [original project](https://github.com/ag2ai/ag2) is licensed under the MIT License as detailed in [LICENSE_original_MIT](./license_original/LICENSE_original_MIT). The fork was created from versio
Remove this change

2024-11-16 23:24 UTC, sonichi commented on NOTICE.md
> +The MIT license applies to portions of code originating from the [original repository](https://github.com/ag2ai/ag2) as described above.
Remove these changes

2024-11-16 23:24 UTC, sonichi commented on README.md
> +- The original code from https://github.com/ag2ai/ag2 is licensed under the MIT License.  See the [LICENSE_original_MIT](./license_original/LICENSE_original_MIT) file for details.
Remove these changes

2024-11-16 23:24 UTC, sonichi commented on TRANSPARENCY_FAQS.md
> +- We also evaluated [a team of AutoGen agents](https://github.com/ag2ai/ag2/tree/gaia_multiagent_v01_march_1st/samples/tools/autogenbench/scenarios/GAIA/Templates/Orchestrator) on the [GAIA benchmark
Remove this change

2024-11-16 23:24 UTC, sonichi commented on website/docs/installation/Docker.md
> +- **ag2ai_base_img**: For a basic setup, you can use the `ag2ai_base_img` to run simple scripts or applications. This is ideal for general users or those new to AG2.
```suggestion
- **ag2_base_img**: For a basic setup, you can use the `ag2_base_img` to run simple scripts or applications. This is ideal for general users or those new to AG2.
```
Please double check if my suggestion is correct.

2024-11-16 23:24 UTC, sonichi commented on website/docs/installation/Docker.md
>  - **ag2ai_full_img**: Advanced users or those requiring more features can use `ag2ai_full_img`. Be aware that this version loads ALL THE THINGS and thus is very large. Take this into consideration if
```suggestion
- **ag2_full_img**: Advanced users or those requiring more features can use `ag2_full_img`. Be aware that this version loads ALL THE THINGS and thus is very large. Take this into consideration if you build your application off of it.
```
Please double check. If the docker file hasn't been renamed in other places, rename them to be consistent.

2024-11-16 23:24 UTC, sonichi commented on website/docs/installation/Docker.md
>    ```
```suggestion
- **AG2 Advanced**: Advanced users or those requiring all the things that AG2 has to offer `ag2_full_img`

  ```bash
  docker build -f .devcontainer/full/Dockerfile -t ag2_full_img https://github.com/ag2ai/ag2.git#main
  ```
```

2024-11-16 23:24 UTC, sonichi commented on website/process_notebooks.py
> +# Portions derived from  https://github.com/ag2ai/ag2 are under the MIT License.
Remove this change

2024-11-16 23:24 UTC, sonichi commented on website/src/components/ExploreContent/ExploreContent.js
> +        Learn how to get start with AG2. Follow the instruction to quickly build-up your first AG2 application.
```suggestion
        Learn how to get started with AG2. Follow the instruction to quickly build-up your first AG2 application.
```

2024-11-16 23:24 UTC, sonichi commented on website/process_notebooks.py
More changes are required to render the notebook properly on the website. Could you test it locally first?

2024-11-17 00:01 UTC, skzhang1 commented on website/docs/installation/Docker.md
> +- **ag2ai_base_img**: For a basic setup, you can use the `ag2ai_base_img` to run simple scripts or applications. This is ideal for general users or those new to AG2.
checked. it is correct.

2024-11-17 00:01 UTC, skzhang1 commented on website/docs/installation/Docker.md
>  - **ag2ai_full_img**: Advanced users or those requiring more features can use `ag2ai_full_img`. Be aware that this version loads ALL THE THINGS and thus is very large. Take this into consideration if
Thanks! checked. it is correct.

2024-11-17 00:02 UTC, skzhang1 commented on website/docs/installation/Docker.md
>    ```
revised

2024-11-17 00:07 UTC, skzhang1 commented on website/process_notebooks.py
It works well locally. Can you share which part is not properly rendered? Let me try to fix it.

2024-11-17 00:10 UTC, sonichi commented on website/process_notebooks.py
For example, https://ag2ai.github.io/autogen/docs/notebooks/JSON_mode_example shows 404. All of the notebook pages show 404.

2024-11-17 00:59 UTC, skzhang1 commented on website/process_notebooks.py
resolved!

2024-11-17 01:22 UTC, skzhang1 commented
@sonichi we can merge this one to fix urgent issues. Fix others in later PR.

2024-11-17 01:24 UTC, merged