ReasoningAgent benchmarking with SimpleBench
ag2ai/ag2 pull request #293
Opened 2024-12-26 14:52 UTC by Hk669

## Why are these changes needed?

a draft PR for running the simple bench with ReasoningAgent.

## Related issue number

## Checks

- [ ] I've included any doc changes needed for https://docs.ag2.ai/. See https://docs.ag2.ai/docs/contributor-guide/documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

2024-12-26 17:12 UTC, sonichi commented
Thanks. How about adding the test into the contrib-openai CI?

2024-12-31 18:56 UTC, BabyCNM commented on benchmark/run_simple-bench.py
> +        answer = eval_set["answer"]
Rename the variable to "ground_truth" to make it more readable.

2024-12-31 18:57 UTC, BabyCNM commented on benchmark/run_simple-bench.py
> +    data = load_data("data.json")
data.json does not exist. Do you mean "simplebench_public.json"?

2024-12-31 18:57 UTC, BabyCNM commented on benchmark/run_simple-bench.py
> +            results.append({"question_id": question_id, "answer": answer, "generated_answer": extracted_answer})
Let's also cache the `ans` and `summary` for debugging purposes.

Also, let's record the accuracy metrics.

2024-12-31 18:58 UTC, BabyCNM requested changes
LGTM. There are some small issues (filename mismatch) that the code would not run.

2025-01-01 10:56 UTC, Hk669 commented on benchmark/run_simple-bench.py
> +            results.append({"question_id": question_id, "answer": answer, "generated_answer": extracted_answer})
ive tried to cache the summary directly with the `results.json`, let me know if this works or is there anything im missing?

2025-01-01 10:58 UTC, Hk669 commented
> Thanks. How about adding the test into the contrib-openai CI?

can you please mention if it is for the ReasoningAgent or for the Benchmark?
fyi: the ci tests for the reasoningagent are under process in the PR https://github.com/ag2ai/ag2/pull/294

2025-01-01 20:36 UTC, sonichi commented
> > Thanks. How about adding the test into the contrib-openai CI?
> 
> can you please mention if it is for the ReasoningAgent or for the Benchmark? fyi: the ci tests for the reasoningagent are under process in the PR #294

I mean, we can add simplebench performance check as an optional CI for reasoning agent. It's only triggered when necessary and requires approval.

2025-01-01 23:26 UTC, marklysze commented
I've tested with Anthropic, Gemini, DeepSeek, committed a summary file.

[See here](https://github.com/ag2ai/ag2/blob/7232dbbbe1ff36084fe77164835d376963f44437/benchmark/simple-bench/2025-01-02-Results.md).

The strongest results are from Anthropic (and Anthropic's chat UI scored the highest).

2025-01-02 04:58 UTC, Hk669 commented
> I've tested with Anthropic, Gemini, DeepSeek, committed a summary file.
> 
> [See here](https://github.com/ag2ai/ag2/blob/7232dbbbe1ff36084fe77164835d376963f44437/benchmark/simple-bench/2025-01-02-Results.md).
> 
> The strongest results are from Anthropic (and Anthropic's chat UI scored the highest).

the numbers are really interesting, i was thinking lets not add in the chat UI results in the benchmarking of the ReasoningAgent, lets just restrict the results to only the reasoning agent?

cc @marklysze @sonichi @BabyCNM

2025-01-02 05:02 UTC, Hk669 commented
> I mean, we can add simplebench performance check as an optional CI for reasoning agent. It's only triggered when necessary and requires approval.

sounds great, let me add the optional CI.

2025-01-02 14:52 UTC, Hk669 commented on benchmark/simple-bench/2025-01-02-Results.md
> +| Q | Correct | Gemini 2.0 Flash Exp<br>ReasoningAgent<br>(LATS, nsim=2, depth=3) | Gemini 2.0 Flash Exp<br>Chat Interface | Gemini 2.0 Flash Thinking Exp<br>Chat Interface | Gemini 1.5 Pro<br>Chat I
```suggestion
| Q | Correct | Gemini 2.0 Flash Exp<br>ReasoningAgent<br>(LATS, nsim=2, depth=3) | Gemini 2.0 Flash Exp<br>Chat Interface | Gemini 2.0 Flash Thinking Exp<br>Chat Interface | Gemini 1.5 Pro<br>Chat Interface | Gemini 2.0 Flash Thinking Exp<br>ReasoningAgent<br>(LATS, nsim=2, depth=3) |
```

2025-01-02 14:52 UTC, Hk669 commented on benchmark/simple-bench/2025-01-02-Results.md
> +| Q | Correct | Gemini 2.0 Flash Exp<br>ReasoningAgent<br>(LATS, nsim=2, depth=3) | Gemini 2.0 Flash Exp<br>Chat Interface | Gemini 2.0 Flash Thinking Exp<br>Chat Interface | Gemini 1.5 Pro<br>Chat I
@marklysze is it with the thinking API or is it duplicate of the gemini 2.0 flash exp? correct me if im wrong. thanks!

2025-01-02 17:26 UTC, Hk669 commented
> Thanks. How about adding the test into the contrib-openai CI?

added. please let me know if i missed anything. thanks!
cc @sonichi

2025-01-02 17:59 UTC, sonichi commented
> > Thanks. How about adding the test into the contrib-openai CI?
> 
> added. please let me know if i missed anything. thanks! cc @sonichi

It's better than before. An even better approach is to make a separate workflow so that it's not bundled with other contrib-openai tests.
@marklysze @BabyCNM @qingyun-wu what do you think is a good balance between convenience and cost control?

2025-01-02 18:17 UTC, marklysze commented on benchmark/simple-bench/2025-01-02-Results.md
> +| Q | Correct | Gemini 2.0 Flash Exp<br>ReasoningAgent<br>(LATS, nsim=2, depth=3) | Gemini 2.0 Flash Exp<br>Chat Interface | Gemini 2.0 Flash Thinking Exp<br>Chat Interface | Gemini 1.5 Pro<br>Chat I
It's with the Thinking model, but whether it's actually performing the thinking, I'm not confident it is because they mention a newer API and some thinking/reasoning flags, so I'm not confident, as noted in Discord.

2025-01-03 07:28 UTC, BabyCNM commented on benchmark/simple_bench/run_simple_bench.py
> +    data = load_data("simplebench_public.json")
set random seed `random.seed(1)` for reproducibility.

2025-01-03 13:39 UTC, Hk669 commented on benchmark/simple_bench/run_simple_bench.py
> +    data = load_data("simplebench_public.json")
ive added this in the other repo. do we need this PR anymore?

2025-02-12 20:30 UTC, davorrunje commented
@Hk669 What is the status with this PR?

2025-02-13 00:31 UTC, Hk669 commented
This is just an experimental PR, for anyone who wanted to run the simplebench on any agent.

2025-02-26 20:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ag2ai/ag2?pullRequest=293) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ag2ai/ag2?pullRequest=293) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: BabyCNM<br/>:white_check_mark: marklysze<br/>:x: Hk669<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ag2ai/ag2?pullRequest=293) it.</sub>

2025-09-16 19:46 UTC, marklysze commented
@Hk669 / @BabyCNM can we close this?

2026-02-22 20:15 UTC, marklysze commented
@Hk669 closing this for now, feel free to reopen if you're able to continue working on it

2026-02-22 20:15 UTC, closed without merging