Update the swarm notebook example
ag2ai/ag2 pull request #62
Opened 2024-11-21 20:53 UTC by yiranwu0

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've included any doc changes needed for https://ag2ai.github.io/ag2/. See https://ag2ai.github.io/ag2/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

2024-11-21 21:29 UTC, qingyun-wu commented on notebook/agentchat_swarm_legacy_w_groupchat.ipynb
> +    "# Implement Swarm with AutoGen GroupChat\n",
Keep the doc consistent

2024-11-21 21:29 UTC, qingyun-wu commented on notebook/agentchat_swarm_legacy_w_groupchat.ipynb
> +    "AutoGen offers conversable agents powered by LLM, tool or human, which can be used to perform tasks collectively via automated chat. Recently, OpenAI has released a [Swarm](https://github.com/op
```suggestion
    "AG2 offers conversable agents powered by LLM, tool or human, which can be used to perform tasks collectively via automated chat. Recently, OpenAI has released a [Swarm](https://github.com/openai/swarm) framework that focuses on making agent coordination and execution lightweight. In autogen, the groupchat allows customized speaker selection, which can be used to achieve the same orchestration pattern. This feature is also supported by our research paper [StateFlow: Enhancing LLM Task-Solving through State-Driven Workflows](https://autogen-ai.github.io/autogen/blog/2024/02/29/StateFlow).\n",
```

2024-11-21 21:53 UTC, marklysze commented
Thanks for the comments, I've resolved and updated as well. Will also update the blog post, so it can be reviewed again and merged after that.

2024-11-21 22:24 UTC, sonichi commented on notebook/agentchat_swarm.ipynb
> +    "Now, AG2 offers a simple programming interface to build and orchestrate a swarm of agents. Please checkout out the [Documentation](https://ag2ai.github.io/ag2/docs/topics/swarm) and [Blog](https
```suggestion
    "Now, AG2 offers a simple programming interface to build and orchestrate a swarm of agents. Please check the [Documentation](https://ag2ai.github.io/ag2/docs/topics/swarm) and [Blog](https://ag2ai.github.io/ag2/blog/2024/11/17/Swarm) for more details.\n",
```

2024-11-21 22:24 UTC, sonichi commented on notebook/agentchat_swarm.ipynb
> +    "For this example, it requires human interaction with the agents. So we pass in an `user` agent, and set the `after_work` parameter to `AfterWorkOption.REVERT_TO_USER`. This means, each time a sw
```suggestion
    "For this example, it requires human interaction with the agents. So we pass in a `user` agent, and set the `after_work` parameter to `AfterWorkOption.REVERT_TO_USER`. This means, each time a swarm agent finishes its work, the conversation will be reverted back to the user to give the next input.\n",
```

2024-11-21 22:24 UTC, sonichi commented on notebook/agentchat_swarm.ipynb
> +    "lost_baggage.register_hand_off(ON_CONDITION(triage_agent, transfer_to_triage_description))"
Is it better to use a for loop?

2024-11-21 22:24 UTC, sonichi commented on notebook/agentchat_swarm_legacy_w_groupchat.ipynb
> +  },
Move this cell to top.

2024-11-21 22:25 UTC, sonichi commented
Is there an obvious benefit of the new swarm programming interface vs. the old one? If so, can we talk about them in doc/blogpost?

2024-11-22 00:19 UTC, yiranwu0 commented on notebook/agentchat_swarm.ipynb
> +    "lost_baggage.register_hand_off(ON_CONDITION(triage_agent, transfer_to_triage_description))"
Yes, Resolved

2024-11-22 00:21 UTC, yiranwu0 commented
> Is there an obvious benefit of the new swarm programming interface vs. the old one? If so, can we talk about them in doc/blogpost?

Yes, will update that

2024-11-22 00:23 UTC, sonichi approved these changes
Shall we merge?

2024-11-22 00:25 UTC, sonichi commented on notebook/agentchat_swarm.ipynb
"description": "Implement Swarm with AutoGen GroupChat",
Can be updated into:
Swarm-style orchestration

2024-11-22 00:26 UTC, sonichi commented on notebook/agentchat_swarm_legacy_w_groupchat.ipynb
> +   "description": "Implement Swarm with AutoGen GroupChat",
```suggestion
   "description": "(Legacy) Implement Swarm-style orchestration with GroupChat",
```

2024-11-22 00:27 UTC, marklysze requested changes

2024-11-22 00:27 UTC, marklysze commented on notebook/agentchat_swarm_legacy_w_groupchat.ipynb
> +    "In AutoGen, the groupchat allows customized speaker selection, which can be used to achieve the same orchestration pattern. This feature is also supported by our research paper [StateFlow: Enhan
```suggestion
    "In AG2, the groupchat allows customized speaker selection, which can be used to achieve the same orchestration pattern. This feature is also supported by our research paper [StateFlow: Enhancing LLM Task-Solving through State-Driven Workflows](https://ag2ai.github.io/ag2/blog/2024/02/29/StateFlow).\n",
```

2024-11-22 00:27 UTC, marklysze commented on notebook/agentchat_swarm_legacy_w_groupchat.ipynb
> +    "> With AutoGen, you don't need to write schemas for functions. You can add decorators to the functions to register a function schema to an LLM-based agent, where the schema is automatically gene
```suggestion
    "> With AG2, you don't need to write schemas for functions. You can add decorators to the functions to register a function schema to an LLM-based agent, where the schema is automatically generated.\n",
```

2024-11-22 00:27 UTC, marklysze commented on notebook/agentchat_swarm_legacy_w_groupchat.ipynb
> +    "In AutoGen, the groupchat allows customized speaker selection, which can be used to achieve the same orchestration pattern. This feature is also supported by our research paper [StateFlow: Enhan
Sorry, can we update these

2024-11-22 00:29 UTC, yiranwu0 commented on notebook/agentchat_swarm_legacy_w_groupchat.ipynb
> +    "In AutoGen, the groupchat allows customized speaker selection, which can be used to achieve the same orchestration pattern. This feature is also supported by our research paper [StateFlow: Enhan
edited.

2024-11-22 00:29 UTC, yiranwu0 commented on notebook/agentchat_swarm_legacy_w_groupchat.ipynb
> +    "> With AutoGen, you don't need to write schemas for functions. You can add decorators to the functions to register a function schema to an LLM-based agent, where the schema is automatically gene
edited.

2024-11-22 00:29 UTC, yiranwu0 commented on notebook/agentchat_swarm_legacy_w_groupchat.ipynb
> +   "description": "Implement Swarm with AutoGen GroupChat",
edited

2024-11-22 00:36 UTC, merged